version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development
      - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.ddev.site
    external_links:
      - 'ddev-router:ddev-slub-katalog.ddev.site'
      - 'ddev-router:katalog.ddev.site'
